require('fs').mkdirSync(require('path').join(__dirname, 'client', 'src', 'components'), { recursive: true });
require('fs').mkdirSync(require('path').join(__dirname, 'client', 'src', 'pages'), { recursive: true });
require('fs').mkdirSync(require('path').join(__dirname, 'client', 'src', 'hooks'), { recursive: true });
require('fs').mkdirSync(require('path').join(__dirname, 'client', 'src', 'stores'), { recursive: true });
require('fs').mkdirSync(require('path').join(__dirname, 'client', 'src', 'services'), { recursive: true });
require('fs').mkdirSync(require('path').join(__dirname, 'client', 'src', 'utils'), { recursive: true });
require('fs').mkdirSync(require('path').join(__dirname, 'client', 'src', 'types'), { recursive: true });
require('fs').mkdirSync(require('path').join(__dirname, 'client', 'src', 'styles'), { recursive: true });
require('fs').mkdirSync(require('path').join(__dirname, 'client', 'public'), { recursive: true });
console.log('Directories created');
